name: Bug report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and what you expected.
      placeholder: "When I run ... it ..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the issue.
      placeholder: |
        1. Start command server
        2. Start agent
        3. Run CLI command ...
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: Paste relevant logs (redact secrets).
      render: shell
    validations:
      required: false

  - type: input
    id: env
    attributes:
      label: Environment
      description: OS + Go version
      placeholder: "Ubuntu 22.04, Go 1.24"
    validations:
      required: true
